### ISSUE TITLE
Coinapult Client RuntimeException error: 0f06707b:elliptic curve routines

### ISSUE THREAD

**Issue by KodeToad** [mycelium-com/wallet-android#411]
I was trying to create a coinapult account in usd. After I accept the terms, the app crashes:

```
Caused by: java.lang.RuntimeException: error: 0f06707b:elliptic curve routines:EC_GROUP_new_by_curve_name:UNKNOWN_GROUP
at com.android.org.conscrypt.NativeCrypto.d2i_PKCS8_PRIV_KEY_INFO(Native Method)
at com.android.org.conscrypt.OpenSSLSignature.engineInitSign(OpenSSLSignature.java:138)
at java.security.Signature$SignatureImpl.engineInitSign(Signature.java:706)
at java.security.Signature.initSign(Signature.java:357)
at com.coinapult.api.httpclient.ECC_SC.generateSign(ECC_SC.java:103)
at com.coinapult.api.httpclient.CoinapultClient.sendECCRequest(CoinapultClient.java:137)

```

**Comment by Giszmo** [comment]
I had noticed a crash on testnet, with that log about elliptic curve, too. As my coinapult accounts on my mainnet wallet still worked, I thought that some testnet stuff on their end was down. Just tried it out and I can't create coinapult accounts on the emulator with mainnet, neither but I also see tons of html with cloudflare being mentioned. Maybe there is some server issue?

[Here is my log](https://gist.github.com/anonymous/fb0d22fdd9d0ef64f3262490c11e4cf8)

**Comment by sergeylappo** [comment]
Closing.
I suppose that this was fixed by https://github.com/mycelium-com/wallet-android/commit/ca1e35f901e3eeb3a1edfb48449a32f0a4141ec2
If would be reproduced again please feel free to reopen.
